package com.aplos.ecommerce.module;

import com.aplos.common.beans.CustomerReview;
import com.aplos.common.beans.PostalZone;
import com.aplos.common.beans.communication.EmailTemplate;
import com.aplos.common.interfaces.ForumUser;
import com.aplos.common.module.AplosModuleImpl;
import com.aplos.common.module.ModuleDbConfig;
import com.aplos.common.persistence.PersistentApplication;
import com.aplos.ecommerce.backingpage.realizedProductReturn.RealizedProductReturnMenuWizard;
import com.aplos.ecommerce.backingpage.transaction.TransactionBackEndMenuWizard;
import com.aplos.ecommerce.backingpage.transaction.TransactionFrontEndMenuWizard;
import com.aplos.ecommerce.beans.Brochure;
import com.aplos.ecommerce.beans.CatalogueRequest;
import com.aplos.ecommerce.beans.ChartAxisValues;
import com.aplos.ecommerce.beans.ChartGridValues;
import com.aplos.ecommerce.beans.Company;
import com.aplos.ecommerce.beans.CompanyContact;
import com.aplos.ecommerce.beans.CompanyType;
import com.aplos.ecommerce.beans.CustomSizeChartAxisLabel;
import com.aplos.ecommerce.beans.Customer;
import com.aplos.ecommerce.beans.CustomerHistory;
import com.aplos.ecommerce.beans.CustomerType;
import com.aplos.ecommerce.beans.DiscountAllowance;
import com.aplos.ecommerce.beans.EcommerceShoppingCart;
import com.aplos.ecommerce.beans.EcommerceShoppingCartItem;
import com.aplos.ecommerce.beans.EcommerceWebsite;
import com.aplos.ecommerce.beans.EmailAFriend;
import com.aplos.ecommerce.beans.EmailAFriendFormSubmission;
import com.aplos.ecommerce.beans.EnticementEmail;
import com.aplos.ecommerce.beans.EnticementEmailPromotion;
import com.aplos.ecommerce.beans.FavouriteProductList;
import com.aplos.ecommerce.beans.FriendReferral;
import com.aplos.ecommerce.beans.GiftVoucher;
import com.aplos.ecommerce.beans.IncludedProduct;
import com.aplos.ecommerce.beans.IncludedProductGroup;
import com.aplos.ecommerce.beans.InfoPackRequest;
import com.aplos.ecommerce.beans.NewsEntry;
import com.aplos.ecommerce.beans.PaymentMethod;
import com.aplos.ecommerce.beans.ProductTypeTechSupport;
import com.aplos.ecommerce.beans.ProductVersion;
import com.aplos.ecommerce.beans.Promotion;
import com.aplos.ecommerce.beans.PromotionConstraint;
import com.aplos.ecommerce.beans.RealizedProduct;
import com.aplos.ecommerce.beans.RealizedProductBand;
import com.aplos.ecommerce.beans.RealizedProductPriceBand;
import com.aplos.ecommerce.beans.RealizedProductReturn;
import com.aplos.ecommerce.beans.ReportStats;
import com.aplos.ecommerce.beans.SerialNumber;
import com.aplos.ecommerce.beans.ShippingBand;
import com.aplos.ecommerce.beans.ShippingBoxOrder;
import com.aplos.ecommerce.beans.SitewideDiscount;
import com.aplos.ecommerce.beans.StoreCreditVoucher;
import com.aplos.ecommerce.beans.Supplier;
import com.aplos.ecommerce.beans.SupplierType;
import com.aplos.ecommerce.beans.Transaction;
import com.aplos.ecommerce.beans.Version;
import com.aplos.ecommerce.beans.WebsiteProductTypeReview;
import com.aplos.ecommerce.beans.amazon.AmazonBrowseNode;
import com.aplos.ecommerce.beans.amazon.AmazonSize;
import com.aplos.ecommerce.beans.couriers.AdditionalShippingOption;
import com.aplos.ecommerce.beans.couriers.ApcInternationalShippingService;
import com.aplos.ecommerce.beans.couriers.ApcUkShippingService;
import com.aplos.ecommerce.beans.couriers.AvailableShippingService;
import com.aplos.ecommerce.beans.couriers.CourierService;
import com.aplos.ecommerce.beans.couriers.FreeShippingService;
import com.aplos.ecommerce.beans.couriers.PostalZoneAdditionalShippingOption;
import com.aplos.ecommerce.beans.couriers.PostalZoneInternationalShippingService;
import com.aplos.ecommerce.beans.couriers.RoyalMailUkShippingService;
import com.aplos.ecommerce.beans.couriers.ShippingBox;
import com.aplos.ecommerce.beans.couriers.ShippingService;
import com.aplos.ecommerce.beans.couriers.ShippingStep;
import com.aplos.ecommerce.beans.couriers.StaticShippingService;
import com.aplos.ecommerce.beans.couriers.WeightGradedShippingService;
import com.aplos.ecommerce.beans.developercmsmodules.AssociatedProductsModule;
import com.aplos.ecommerce.beans.developercmsmodules.BrochureCmsAtom;
import com.aplos.ecommerce.beans.developercmsmodules.CategoryListModule;
import com.aplos.ecommerce.beans.developercmsmodules.CategoryOverviewModule;
import com.aplos.ecommerce.beans.developercmsmodules.CheckoutPaymentCmsAtom;
import com.aplos.ecommerce.beans.developercmsmodules.CrossSellingModule;
import com.aplos.ecommerce.beans.developercmsmodules.FavouriteProductListsCmsAtom;
import com.aplos.ecommerce.beans.developercmsmodules.ForgottenPasswordModule;
import com.aplos.ecommerce.beans.developercmsmodules.ForgottenPasswordResetModule;
import com.aplos.ecommerce.beans.developercmsmodules.FriendReferralModule;
import com.aplos.ecommerce.beans.developercmsmodules.LatestProductListModule;
import com.aplos.ecommerce.beans.developercmsmodules.MyDetailsModule;
import com.aplos.ecommerce.beans.developercmsmodules.NewsModule;
import com.aplos.ecommerce.beans.developercmsmodules.ProductListModule;
import com.aplos.ecommerce.beans.developercmsmodules.ProductTypeReviewCmsAtom;
import com.aplos.ecommerce.beans.developercmsmodules.ProductTypeTechSupportCmsAtom;
import com.aplos.ecommerce.beans.developercmsmodules.SaleProductListModule;
import com.aplos.ecommerce.beans.developercmsmodules.SearchProductListModule;
import com.aplos.ecommerce.beans.developercmsmodules.SizeChartModule;
import com.aplos.ecommerce.beans.ebay.EbayCategoryManager;
import com.aplos.ecommerce.beans.ebay.EbayPersistentCategory;
import com.aplos.ecommerce.beans.forum.ForumPost;
import com.aplos.ecommerce.beans.forum.ForumThread;
import com.aplos.ecommerce.beans.playcom.PlayColour;
import com.aplos.ecommerce.beans.playcom.PlayGender;
import com.aplos.ecommerce.beans.playcom.PlayMainGenre;
import com.aplos.ecommerce.beans.playcom.PlayProductType;
import com.aplos.ecommerce.beans.playcom.PlaySize;
import com.aplos.ecommerce.beans.playcom.PlaySizeType;
import com.aplos.ecommerce.beans.playcom.PlaySubGenre;
import com.aplos.ecommerce.beans.product.Product;
import com.aplos.ecommerce.beans.product.ProductBrand;
import com.aplos.ecommerce.beans.product.ProductColour;
import com.aplos.ecommerce.beans.product.ProductFaq;
import com.aplos.ecommerce.beans.product.ProductGroup;
import com.aplos.ecommerce.beans.product.ProductInfo;
import com.aplos.ecommerce.beans.product.ProductSize;
import com.aplos.ecommerce.beans.product.ProductSizeCategory;
import com.aplos.ecommerce.beans.product.ProductSizeChart;
import com.aplos.ecommerce.beans.product.ProductSizeType;
import com.aplos.ecommerce.beans.product.ProductType;
import com.aplos.ecommerce.interfaces.ProductListRoot;
import com.aplos.ecommerce.interfaces.RealizedProductRetriever;
import com.aplos.ecommerce.interfaces.SerialNumberOwner;
import com.aplos.ecommerce.interfaces.SizeChartAxisLabel;
import com.aplos.ecommerce.scheduledjobs.AbandonedOrderEmailerJob;
import com.aplos.ecommerce.scheduledjobs.RecordReportStatsJob;
import com.aplos.ecommerce.scheduledjobs.RepeatCustomIncentiveEmailer;
import com.aplos.ecommerce.templates.emailtemplates.AbandonedTransactionEmail;
import com.aplos.ecommerce.templates.emailtemplates.AcknowledgementEmail;
import com.aplos.ecommerce.templates.emailtemplates.AwaitingAuthorisationEmail;
import com.aplos.ecommerce.templates.emailtemplates.CalibrationCertificateEmail;
import com.aplos.ecommerce.templates.emailtemplates.CancellationNoticeEmail;
import com.aplos.ecommerce.templates.emailtemplates.ConditionReceivedReportEmail;
import com.aplos.ecommerce.templates.emailtemplates.ConfirmPaymentEmail;
import com.aplos.ecommerce.templates.emailtemplates.CourierDetailsEmail;
import com.aplos.ecommerce.templates.emailtemplates.CustomerEmailConfirmationEmail;
import com.aplos.ecommerce.templates.emailtemplates.CustomerSignupEmail;
import com.aplos.ecommerce.templates.emailtemplates.DispatchInvoiceEmail;
import com.aplos.ecommerce.templates.emailtemplates.DispatchNoteEmail;
import com.aplos.ecommerce.templates.emailtemplates.DispatchNotificationEmail;
import com.aplos.ecommerce.templates.emailtemplates.EcommerceInvoiceEmail;
import com.aplos.ecommerce.templates.emailtemplates.EmailAFriendEmail;
import com.aplos.ecommerce.templates.emailtemplates.EnticementEmailTemplate;
import com.aplos.ecommerce.templates.emailtemplates.FirstHookEmail;
import com.aplos.ecommerce.templates.emailtemplates.ForgottenPasswordEmail;
import com.aplos.ecommerce.templates.emailtemplates.FriendReferralAdminEmail;
import com.aplos.ecommerce.templates.emailtemplates.FriendReferralEmail;
import com.aplos.ecommerce.templates.emailtemplates.GiftVoucherIssuedEmail;
import com.aplos.ecommerce.templates.emailtemplates.InfoPackAdminEmail;
import com.aplos.ecommerce.templates.emailtemplates.InfoPackEmail;
import com.aplos.ecommerce.templates.emailtemplates.LoanEmail;
import com.aplos.ecommerce.templates.emailtemplates.PaymentFailedEmail;
import com.aplos.ecommerce.templates.emailtemplates.PdfConfirmPaymentEmail;
import com.aplos.ecommerce.templates.emailtemplates.ProFormaEmail;
import com.aplos.ecommerce.templates.emailtemplates.QuoteEmail;
import com.aplos.ecommerce.templates.emailtemplates.ReferralPayoutIssuedEmail;
import com.aplos.ecommerce.templates.emailtemplates.RepairReportEmail;
import com.aplos.ecommerce.templates.emailtemplates.ResetPasswordEmail;
import com.aplos.ecommerce.templates.emailtemplates.ReturnsAuthorisationNoteEmail;
import com.aplos.ecommerce.templates.emailtemplates.ReturnsEmail;
import com.aplos.ecommerce.templates.emailtemplates.SecondHookEmail;
import com.aplos.ecommerce.templates.emailtemplates.ThirdHookEmail;
import com.aplos.ecommerce.templates.emailtemplates.TransactionEmail;
import com.aplos.ecommerce.templates.printtemplates.CalibrationCertificateTemplate;
import com.aplos.ecommerce.templates.printtemplates.ConditionReceivedReportTemplate;
import com.aplos.ecommerce.templates.printtemplates.DispatchInvoiceTemplate;
import com.aplos.ecommerce.templates.printtemplates.DispatchNoteTemplate;
import com.aplos.ecommerce.templates.printtemplates.EcommerceInvoiceTemplate;
import com.aplos.ecommerce.templates.printtemplates.LoanFormTemplate;
import com.aplos.ecommerce.templates.printtemplates.ProFormaTemplate;
import com.aplos.ecommerce.templates.printtemplates.QuoteTemplate;
import com.aplos.ecommerce.templates.printtemplates.RepairReportTemplate;
import com.aplos.ecommerce.templates.printtemplates.ReturnsAuthorisationNoteTemplate;
import com.aplos.ecommerce.templates.printtemplates.ReturnsTemplate;
import com.aplos.ecommerce.templates.printtemplates.TransactionAcknowledgementTemplate;
import com.aplos.ecommerce.templates.printtemplates.TransactionTemplate;

public class EcommerceModuleDbConfig extends ModuleDbConfig {

	public EcommerceModuleDbConfig( AplosModuleImpl aplosModule ) {
		super(aplosModule);
	}

//	@Override
//	public void includeAllTables() {
//	}

	@Override
	public void addAnnotatedClass(PersistentApplication persistentApplication) {
		persistentApplication.addPersistentClass( EcommerceWebsite.class, true );
		persistentApplication.addPersistentClass( Customer.class, true );
		persistentApplication.addPersistentClass( NewsEntry.class, true );
		persistentApplication.addPersistentClass( NewsModule.class, true );
    	persistentApplication.addPersistentClass( EcommerceConfiguration.class, true );
    	persistentApplication.addPersistentClass( Transaction.class, true );
    	persistentApplication.addPersistentClass( Promotion.class, true );
    	persistentApplication.addPersistentClass( PromotionConstraint.class, true );
    	persistentApplication.addPersistentClass( Product.class, true );
    	persistentApplication.addPersistentClass( ProductVersion.class, true );
    	persistentApplication.addPersistentClass( ProductInfo.class, true );
    	persistentApplication.addPersistentClass( ProductBrand.class, true );
    	persistentApplication.addPersistentClass( ProductColour.class, true );
    	persistentApplication.addPersistentClass( PostalZone.class, true );
    	persistentApplication.addPersistentClass( ForumThread.class, true );
    	persistentApplication.addPersistentClass( ForumPost.class, true );
    	persistentApplication.addPersistentClass( ProductType.class, true );
    	persistentApplication.addPersistentClass( FavouriteProductList.class, true );
    	persistentApplication.addPersistentClass( ProductSizeType.class, true );
    	persistentApplication.addPersistentClass( ProductSize.class, true );
    	persistentApplication.addPersistentClass( RealizedProduct.class, true );
    	persistentApplication.addPersistentClass( EcommerceShoppingCartItem.class, true );
    	persistentApplication.addPersistentClass( EbayCategoryManager.class, true );
    	persistentApplication.addPersistentClass( EbayPersistentCategory.class, true );
    	persistentApplication.addPersistentClass( CategoryListModule.class, true );
    	persistentApplication.addPersistentClass( CategoryOverviewModule.class, true );
    	persistentApplication.addPersistentClass( ProductListModule.class, true );
    	persistentApplication.addPersistentClass( FavouriteProductListsCmsAtom.class, true );
    	persistentApplication.addPersistentClass( ProductTypeTechSupportCmsAtom.class, true );
    	persistentApplication.addPersistentClass( ProductTypeReviewCmsAtom.class, true );
    	persistentApplication.addPersistentClass( SearchProductListModule.class, true );
    	persistentApplication.addPersistentClass( LatestProductListModule.class, true );
    	persistentApplication.addPersistentClass( SaleProductListModule.class, true );
    	persistentApplication.addPersistentClass( ForgottenPasswordModule.class, true );
    	persistentApplication.addPersistentClass( ForgottenPasswordResetModule.class, true );
    	persistentApplication.addPersistentClass( MyDetailsModule.class, true );
    	persistentApplication.addPersistentClass( AssociatedProductsModule.class, true );
    	persistentApplication.addPersistentClass( CrossSellingModule.class, true );
    	persistentApplication.addPersistentClass( EcommerceConfiguration.class, true );
    	persistentApplication.addPersistentClass( PaymentMethod.class, true );
    	persistentApplication.addPersistentClass( ShippingStep.class, true );
    	persistentApplication.addPersistentClass( ShippingService.class, true );
    	persistentApplication.addPersistentClass( AvailableShippingService.class, true );
    	persistentApplication.addPersistentClass( AdditionalShippingOption.class, true );
    	persistentApplication.addPersistentClass( ApcInternationalShippingService.class, true );
    	persistentApplication.addPersistentClass( ApcUkShippingService.class, true );
    	persistentApplication.addPersistentClass( RoyalMailUkShippingService.class, true );
    	persistentApplication.addPersistentClass( PostalZoneInternationalShippingService.class, true );
    	persistentApplication.addPersistentClass( PostalZoneAdditionalShippingOption.class, true );
    	persistentApplication.addPersistentClass( FreeShippingService.class, true );
    	persistentApplication.addPersistentClass( EcommerceSettings.class, true );
    	persistentApplication.addPersistentClass( ProductFaq.class, true );
    	persistentApplication.addPersistentClass( CustomerReview.class, true );
    	persistentApplication.addPersistentClass( CustomerHistory.class, true );
    	persistentApplication.addPersistentClass( WebsiteProductTypeReview.class, true );
    	persistentApplication.addPersistentClass( ProductTypeTechSupport.class, true );
    	persistentApplication.addPersistentClass( ShippingBox.class, true );
    	persistentApplication.addPersistentClass( ShippingBoxOrder.class, true );
    	persistentApplication.addPersistentClass( CheckoutPaymentCmsAtom.class, true );
    	persistentApplication.addPersistentClass( CustomerType.class, true );
    	persistentApplication.addPersistentClass( ProductSizeCategory.class, true );
    	persistentApplication.addPersistentClass( IncludedProduct.class, true );
    	persistentApplication.addPersistentClass( ProductGroup.class, true );
    	persistentApplication.addPersistentClass( GiftVoucher.class, true );
    	persistentApplication.addPersistentClass( StoreCreditVoucher.class, true );
    	persistentApplication.addPersistentClass( Company.class, true );
    	persistentApplication.addPersistentClass( CompanyContact.class, true );
    	persistentApplication.addPersistentClass( CompanyType.class, true );
    	persistentApplication.addPersistentClass( StaticShippingService.class, true );
    	persistentApplication.addPersistentClass( WeightGradedShippingService.class, true );
    	persistentApplication.addPersistentClass( EmailTemplate.class, true );
    	persistentApplication.addPersistentClass( CourierService.class, true );
    	persistentApplication.addPersistentClass( EcommerceShoppingCart.class, true );
//    	persistentApplication.addPersistentClass( Transaction.class, true );
    	persistentApplication.addPersistentClass( RealizedProductReturn.class, true );
    	persistentApplication.addPersistentClass( SerialNumber.class, true );
    	persistentApplication.addPersistentClass( Version.class, true );
    	persistentApplication.addPersistentClass( SitewideDiscount.class, true );
    	persistentApplication.addPersistentClass( CatalogueRequest.class, true );
    	persistentApplication.addPersistentClass( FriendReferralModule.class, true );
    	persistentApplication.addPersistentClass( FriendReferral.class, true );
    	persistentApplication.addPersistentClass( IncludedProductGroup.class, true );
    	persistentApplication.addPersistentClass( EmailAFriend.class, true );
    	persistentApplication.addPersistentClass( ProductSizeChart.class, true );
    	persistentApplication.addPersistentClass( SizeChartModule.class, true );
    	persistentApplication.addPersistentClass( ShippingBand.class, true );
    	persistentApplication.addPersistentClass( BrochureCmsAtom.class, true );
    	persistentApplication.addPersistentClass( Brochure.class, false );
    	persistentApplication.addPersistentClass( EnticementEmailPromotion.class, true );
    	persistentApplication.addPersistentClass( EnticementEmailTemplate.class, true );
    	persistentApplication.addPersistentClass( RealizedProductBand.class, true );
    	persistentApplication.addPersistentClass( RealizedProductPriceBand.class, true );
    	persistentApplication.addPersistentClass( CustomSizeChartAxisLabel.class, true );
    	persistentApplication.addPersistentClass( ChartAxisValues.class, true );
    	persistentApplication.addPersistentClass( ChartGridValues.class, true );
    	persistentApplication.addPersistentClass( InfoPackRequest.class, true );
    	persistentApplication.addPersistentClass( InfoPackEmail.class, true );
    	persistentApplication.addPersistentClass( InfoPackAdminEmail.class, true );
    	persistentApplication.addPersistentClass( AmazonSize.class, true );
    	persistentApplication.addPersistentClass( EmailAFriendFormSubmission.class, true );

    	persistentApplication.addPersistentClass( ReportStats.class, true );

    	persistentApplication.addPersistentClass( Supplier.class, true );
    	persistentApplication.addPersistentClass( SupplierType.class, true );
    	
    	persistentApplication.addPersistentClass( PlayGender.class, true );
    	persistentApplication.addPersistentClass( PlayMainGenre.class, true );
    	persistentApplication.addPersistentClass( PlaySubGenre.class, true );
    	persistentApplication.addPersistentClass( PlayProductType.class, true );
    	persistentApplication.addPersistentClass( PlaySizeType.class, true );
    	persistentApplication.addPersistentClass( PlaySize.class, true );
    	persistentApplication.addPersistentClass( PlayColour.class, true );
    	
    	persistentApplication.addPersistentClass( AmazonBrowseNode.class, true );

    	//  EmailTemplates
    	persistentApplication.addPersistentClass( CourierDetailsEmail.class, true );
    	persistentApplication.addPersistentClass( ConfirmPaymentEmail.class, true );
    	persistentApplication.addPersistentClass( EnticementEmail.class, true );
    	persistentApplication.addPersistentClass( DispatchNoteEmail.class, true );
    	persistentApplication.addPersistentClass( CancellationNoticeEmail.class, true );
    	persistentApplication.addPersistentClass( AwaitingAuthorisationEmail.class, true );
    	persistentApplication.addPersistentClass( AcknowledgementEmail.class, true );
    	persistentApplication.addPersistentClass( PdfConfirmPaymentEmail.class, true );
    	persistentApplication.addPersistentClass( CustomerSignupEmail.class, true );
    	persistentApplication.addPersistentClass( DispatchNotificationEmail.class, true );
    	persistentApplication.addPersistentClass( EmailAFriendEmail.class, true );
    	persistentApplication.addPersistentClass( ForgottenPasswordEmail.class, true );
    	persistentApplication.addPersistentClass( PaymentFailedEmail.class, true );
    	persistentApplication.addPersistentClass( ResetPasswordEmail.class, true );
    	persistentApplication.addPersistentClass( ReturnsEmail.class, true );
    	persistentApplication.addPersistentClass( ReturnsAuthorisationNoteEmail.class, true );
    	persistentApplication.addPersistentClass( ConditionReceivedReportEmail.class, true );
    	persistentApplication.addPersistentClass( CalibrationCertificateEmail.class, true );
    	persistentApplication.addPersistentClass( RepairReportEmail.class, true );
    	persistentApplication.addPersistentClass( TransactionEmail.class, true );
    	persistentApplication.addPersistentClass( QuoteEmail.class, true );
    	persistentApplication.addPersistentClass( GiftVoucherIssuedEmail.class, true );
    	persistentApplication.addPersistentClass( ReferralPayoutIssuedEmail.class, true );
    	persistentApplication.addPersistentClass( FirstHookEmail.class, true );
    	persistentApplication.addPersistentClass( SecondHookEmail.class, true );
    	persistentApplication.addPersistentClass( ThirdHookEmail.class, true );
    	persistentApplication.addPersistentClass( CustomerEmailConfirmationEmail.class, true );
    	persistentApplication.addPersistentClass( FriendReferralEmail.class, true );
    	persistentApplication.addPersistentClass( FriendReferralAdminEmail.class, true );
    	persistentApplication.addPersistentClass( LoanEmail.class, true );
    	persistentApplication.addPersistentClass( DispatchInvoiceEmail.class, true );
    	persistentApplication.addPersistentClass( ProFormaEmail.class, true );
    	persistentApplication.addPersistentClass( EcommerceInvoiceEmail.class, true );
    	persistentApplication.addPersistentClass( AbandonedTransactionEmail.class, true );

		persistentApplication.addPersistentClass( AbandonedOrderEmailerJob.class, true );
		persistentApplication.addPersistentClass( RecordReportStatsJob.class, true );
		persistentApplication.addPersistentClass( RepeatCustomIncentiveEmailer.class, true );

    	// PrintTemplates
    	persistentApplication.addPersistentClass( TransactionTemplate.class, true );
    	persistentApplication.addPersistentClass( QuoteTemplate.class, true );
    	persistentApplication.addPersistentClass( ReturnsTemplate.class, true );
    	persistentApplication.addPersistentClass( ReturnsAuthorisationNoteTemplate.class, true );
    	persistentApplication.addPersistentClass( ConditionReceivedReportTemplate.class, true );
    	persistentApplication.addPersistentClass( CalibrationCertificateTemplate.class, true );
    	persistentApplication.addPersistentClass( RepairReportTemplate.class, true );
    	persistentApplication.addPersistentClass( DispatchInvoiceTemplate.class, true );
    	persistentApplication.addPersistentClass( DispatchNoteTemplate.class, true );
    	persistentApplication.addPersistentClass( EcommerceInvoiceTemplate.class, true );
    	persistentApplication.addPersistentClass( LoanFormTemplate.class, true );
    	persistentApplication.addPersistentClass( ProFormaTemplate.class, true );
    	persistentApplication.addPersistentClass( TransactionAcknowledgementTemplate.class, true );
    	

    	// interfaces

    	persistentApplication.addPersistentClass( ForumUser.class );
    	persistentApplication.addPersistentClass( RealizedProductRetriever.class );
    	persistentApplication.addPersistentClass( AvailableShippingService.class );
    	persistentApplication.addPersistentClass( ProductListRoot.class );
    	persistentApplication.addPersistentClass( SizeChartAxisLabel.class );
    	persistentApplication.addPersistentClass( SerialNumberOwner.class );

    	persistentApplication.addPersistentClass( RealizedProductReturnMenuWizard.class );
    	persistentApplication.addPersistentClass( TransactionBackEndMenuWizard.class );
    	persistentApplication.addPersistentClass( TransactionFrontEndMenuWizard.class );
    	persistentApplication.addPersistentClass( DiscountAllowance.class );
    	persistentApplication.addPersistentClass( EcommerceCmsPageRevisions.class );
	}
}
